// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#ifndef _UI_COMP_LEFTPANEL_H
#define _UI_COMP_LEFTPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LeftPanel
#define UI_COMP_LEFTPANEL_LEFTPANEL 0
#define UI_COMP_LEFTPANEL_MAIN_BUTTON 1
#define UI_COMP_LEFTPANEL_MAIN_BUTTON_LABEL4 2
#define UI_COMP_LEFTPANEL_PRAYERS_BUTTON 3
#define UI_COMP_LEFTPANEL_PRAYERS_BUTTON_LABEL6 4
#define UI_COMP_LEFTPANEL_SETUP_BUTTON 5
#define UI_COMP_LEFTPANEL_SETUP_BUTTON_LABEL5 6
#define UI_COMP_LEFTPANEL_SETTINGS_BUTTON 7
#define UI_COMP_LEFTPANEL_SETTINGS_BUTTON_LABEL3 8
#define _UI_COMP_LEFTPANEL_NUM 9
lv_obj_t * ui_LeftPanel_create(lv_obj_t * comp_parent);
void ui_event_comp_LeftPanel_Main_Button(lv_event_t * e);
void ui_event_comp_LeftPanel_Prayers_Button(lv_event_t * e);
void ui_event_comp_LeftPanel_Setup_Button(lv_event_t * e);
void ui_event_comp_LeftPanel_Settings_Button(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
