// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#include "../ui.h"

void ui_Loading_Screen_screen_init(void)
{
    ui_Loading_Screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Loading_Screen, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loading_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background2 = lv_img_create(ui_Loading_Screen);
    lv_img_set_src(ui_Background2, &ui_img_minaret_bg_png);
    lv_obj_set_width(ui_Background2, 800);
    lv_obj_set_height(ui_Background2, 480);
    lv_obj_set_align(ui_Background2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Loading_Screen, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 50);
    lv_obj_set_height(ui_Spinner2, 50);
    lv_obj_set_x(ui_Spinner2, 50);
    lv_obj_set_y(ui_Spinner2, 0);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xAF7017), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Loading_Status_Text = lv_label_create(ui_Loading_Screen);
    lv_obj_set_width(ui_Loading_Status_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Loading_Status_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Loading_Status_Text, 43);
    lv_obj_set_y(ui_Loading_Status_Text, -20);
    lv_obj_set_align(ui_Loading_Status_Text, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Loading_Status_Text, "Initializing...");
    lv_obj_set_style_text_color(ui_Loading_Status_Text, lv_color_hex(0x633804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Loading_Status_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Loading_Status_Text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);


}
