// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#include "../ui.h"

void ui_Main_Screen_screen_init(void)
{
    ui_Main_Screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Main_Screen, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Background, &ui_img_minaret_bg_png);
    lv_obj_set_width(ui_Background, 800);
    lv_obj_set_height(ui_Background, 480);
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_S1_Content_Panel = lv_obj_create(ui_Main_Screen);
    lv_obj_set_width(ui_S1_Content_Panel, 720);
    lv_obj_set_height(ui_S1_Content_Panel, 430);
    lv_obj_set_align(ui_S1_Content_Panel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_S1_Content_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer_Panel = lv_obj_create(ui_S1_Content_Panel);
    lv_obj_set_width(ui_Next_Prayer_Panel, 343);
    lv_obj_set_height(ui_Next_Prayer_Panel, 144);
    lv_obj_set_x(ui_Next_Prayer_Panel, 0);
    lv_obj_set_y(ui_Next_Prayer_Panel, -20);
    lv_obj_set_align(ui_Next_Prayer_Panel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Next_Prayer_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Next_Prayer_Panel, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Next_Prayer_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Next_Prayer_Panel, lv_color_hex(0xBB7910), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Next_Prayer_Panel, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Next_Prayer_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Next_Prayer_Panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Next_Prayer_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Next_Prayer_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Next_Prayer_Panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Next_Prayer_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Next_Prayer_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Next_Prayer_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Next_Prayer_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer = lv_label_create(ui_Next_Prayer_Panel);
    lv_obj_set_width(ui_Next_Prayer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Prayer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Next_Prayer, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Next_Prayer, "--");
    lv_obj_set_style_text_color(ui_Next_Prayer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next_Prayer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Next_Prayer, &ui_font_Montserrat_SemiBold_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer_Remaining = lv_label_create(ui_Next_Prayer_Panel);
    lv_obj_set_width(ui_Next_Prayer_Remaining, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Prayer_Remaining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next_Prayer_Remaining, 10);
    lv_obj_set_y(ui_Next_Prayer_Remaining, 0);
    lv_obj_set_align(ui_Next_Prayer_Remaining, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Next_Prayer_Remaining, "00:00");
    lv_obj_set_style_text_color(ui_Next_Prayer_Remaining, lv_color_hex(0x00FF37), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next_Prayer_Remaining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Next_Prayer_Remaining, &ui_font_Montserrat_SemiBold_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer_Time = lv_label_create(ui_Next_Prayer_Panel);
    lv_obj_set_width(ui_Next_Prayer_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Prayer_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next_Prayer_Time, -10);
    lv_obj_set_y(ui_Next_Prayer_Time, -16);
    lv_obj_set_align(ui_Next_Prayer_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Next_Prayer_Time, "00:00 AM");
    lv_obj_set_style_text_color(ui_Next_Prayer_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next_Prayer_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Next_Prayer_Time, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Current_Time = lv_label_create(ui_S1_Content_Panel);
    lv_obj_set_width(ui_Current_Time, 700);
    lv_obj_set_height(ui_Current_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Current_Time, 10);
    lv_obj_set_y(ui_Current_Time, -70);
    lv_obj_set_align(ui_Current_Time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Current_Time, "00:00\nAM");
    lv_obj_set_style_text_color(ui_Current_Time, lv_color_hex(0x9F4400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Current_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Current_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Current_Time, -20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Current_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Current_Time, &ui_font_Montserrat_SemiBold_110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Current_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Current_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Current_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Current_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Condition_Panel = lv_obj_create(ui_S1_Content_Panel);
    lv_obj_set_width(ui_Weather_Condition_Panel, 152);
    lv_obj_set_height(ui_Weather_Condition_Panel, 144);
    lv_obj_set_x(ui_Weather_Condition_Panel, -20);
    lv_obj_set_y(ui_Weather_Condition_Panel, -20);
    lv_obj_set_align(ui_Weather_Condition_Panel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Weather_Condition_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Condition_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Condition_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Weather_Condition_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Weather_Condition_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Weather_Condition_Panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image = lv_img_create(ui_Weather_Condition_Panel);
    lv_obj_set_width(ui_Weather_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weather_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Weather_Image, 200);

    ui_Weather_Condition_Panel1 = lv_obj_create(ui_S1_Content_Panel);
    lv_obj_set_width(ui_Weather_Condition_Panel1, 154);
    lv_obj_set_height(ui_Weather_Condition_Panel1, 144);
    lv_obj_set_x(ui_Weather_Condition_Panel1, 20);
    lv_obj_set_y(ui_Weather_Condition_Panel1, -20);
    lv_obj_set_align(ui_Weather_Condition_Panel1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Weather_Condition_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Condition_Panel1, lv_color_hex(0xFDD17D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Condition_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Weather_Condition_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Weather_Condition_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Weather_Condition_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Weather_Condition_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Weather_Condition_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Current_Date = lv_label_create(ui_Weather_Condition_Panel1);
    lv_obj_set_width(ui_Current_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Current_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Current_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Current_Date, "---");
    lv_obj_set_style_text_color(ui_Current_Date, lv_color_hex(0x805700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Current_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Current_Date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Current_Date, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_Panel_Main = ui_LeftPanel_create(ui_Main_Screen);
    lv_obj_set_x(ui_Left_Panel_Main, -1);
    lv_obj_set_y(ui_Left_Panel_Main, 0);

    lv_obj_add_state(ui_comp_get_child(ui_Left_Panel_Main, UI_COMP_LEFTPANEL_MAIN_BUTTON),
                     LV_STATE_FOCUSED);       /// States









}
