// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#include "../ui.h"

void ui_Prayers_Screen_screen_init(void)
{
    ui_Prayers_Screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Prayers_Screen, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Prayers_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background3 = lv_img_create(ui_Prayers_Screen);
    lv_img_set_src(ui_Background3, &ui_img_minaret_bg_png);
    lv_obj_set_width(ui_Background3, 800);
    lv_obj_set_height(ui_Background3, 480);
    lv_obj_set_align(ui_Background3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_S1_Content_Panel1 = lv_obj_create(ui_Prayers_Screen);
    lv_obj_set_width(ui_S1_Content_Panel1, 720);
    lv_obj_set_height(ui_S1_Content_Panel1, 430);
    lv_obj_set_align(ui_S1_Content_Panel1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_S1_Content_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer_Panel1 = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_Next_Prayer_Panel1, 345);
    lv_obj_set_height(ui_Next_Prayer_Panel1, 144);
    lv_obj_set_x(ui_Next_Prayer_Panel1, -175);
    lv_obj_set_y(ui_Next_Prayer_Panel1, -21);
    lv_obj_set_align(ui_Next_Prayer_Panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Next_Prayer_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Next_Prayer_Panel1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Next_Prayer_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Next_Prayer_Panel1, lv_color_hex(0xBB7910), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Next_Prayer_Panel1, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Next_Prayer_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Next_Prayer_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Next_Prayer_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Next_Prayer_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Next_Prayer_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Next_Prayer_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Next_Prayer_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Next_Prayer_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Next_Prayer_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer1 = lv_label_create(ui_Next_Prayer_Panel1);
    lv_obj_set_width(ui_Next_Prayer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Prayer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Next_Prayer1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Next_Prayer1, "Fajr");
    lv_obj_set_style_text_color(ui_Next_Prayer1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next_Prayer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Next_Prayer1, &ui_font_Montserrat_SemiBold_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer_Remaining1 = lv_label_create(ui_Next_Prayer_Panel1);
    lv_obj_set_width(ui_Next_Prayer_Remaining1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Prayer_Remaining1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next_Prayer_Remaining1, 10);
    lv_obj_set_y(ui_Next_Prayer_Remaining1, 0);
    lv_obj_set_align(ui_Next_Prayer_Remaining1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Next_Prayer_Remaining1, "05:00");
    lv_obj_set_style_text_color(ui_Next_Prayer_Remaining1, lv_color_hex(0xFFFCCA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next_Prayer_Remaining1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Next_Prayer_Remaining1, &ui_font_Montserrat_SemiBold_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Next_Prayer_Time1 = lv_label_create(ui_Next_Prayer_Panel1);
    lv_obj_set_width(ui_Next_Prayer_Time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Next_Prayer_Time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Next_Prayer_Time1, -10);
    lv_obj_set_y(ui_Next_Prayer_Time1, -16);
    lv_obj_set_align(ui_Next_Prayer_Time1, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Next_Prayer_Time1, "08:25 PM");
    lv_obj_set_style_text_color(ui_Next_Prayer_Time1, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Next_Prayer_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Next_Prayer_Time1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date_Panel1 = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_Date_Panel1, 350);
    lv_obj_set_height(ui_Date_Panel1, 100);
    lv_obj_set_x(ui_Date_Panel1, -207);
    lv_obj_set_y(ui_Date_Panel1, 510);
    lv_obj_set_align(ui_Date_Panel1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Date_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Date_Panel1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Date_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Date_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Date_Panel1, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Date_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Date_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Date_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT1 = lv_obj_create(ui_Date_Panel1);
    lv_obj_set_height(ui_DT1, 70);
    lv_obj_set_width(ui_DT1, lv_pct(50));
    lv_obj_set_align(ui_DT1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_DT1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Head_Temp1 = lv_label_create(ui_DT1);
    lv_obj_set_width(ui_Label_Head_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Head_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Head_Temp1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Head_Temp1, "Nov 24");
    lv_obj_set_style_text_color(ui_Label_Head_Temp1, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Head_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Head_Temp1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Printing_Head_Temp_1 = lv_label_create(ui_DT1);
    lv_obj_set_width(ui_Label_Printing_Head_Temp_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Printing_Head_Temp_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Printing_Head_Temp_1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Printing_Head_Temp_1, "2024");
    lv_label_set_recolor(ui_Label_Printing_Head_Temp_1, "true");
    lv_obj_set_style_text_color(ui_Label_Printing_Head_Temp_1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Printing_Head_Temp_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Printing_Head_Temp_1, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Date_Panel1);
    lv_obj_set_width(ui_Panel3, 2);
    lv_obj_set_height(ui_Panel3, 58);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT3_copy1 = lv_obj_create(ui_Date_Panel1);
    lv_obj_set_height(ui_DT3_copy1, 70);
    lv_obj_set_width(ui_DT3_copy1, lv_pct(50));
    lv_obj_set_align(ui_DT3_copy1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DT3_copy1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT3_copy1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT3_copy1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT3_copy1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT3_copy1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT3_copy1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT3_copy1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT3_copy1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT3_copy1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT3_copy1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Bed_Temp1 = lv_label_create(ui_DT3_copy1);
    lv_obj_set_width(ui_Label_Bed_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Bed_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Bed_Temp1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Bed_Temp1, "Jumadah 22");
    lv_obj_set_style_text_color(ui_Label_Bed_Temp1, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Bed_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Bed_Temp1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Printing_Bed_Temp2 = lv_label_create(ui_DT3_copy1);
    lv_obj_set_width(ui_Label_Printing_Bed_Temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Printing_Bed_Temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Printing_Bed_Temp2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Printing_Bed_Temp2, "1446AH");
    lv_label_set_recolor(ui_Label_Printing_Bed_Temp2, "true");
    lv_obj_set_style_text_color(ui_Label_Printing_Bed_Temp2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Printing_Bed_Temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Printing_Bed_Temp2, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Date_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 10);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "Wednesday");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Current_Time1 = lv_label_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_Current_Time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Current_Time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Current_Time1, 25);
    lv_obj_set_y(ui_Current_Time1, -70);
    lv_obj_set_align(ui_Current_Time1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Current_Time1, "05:00\nPM");
    lv_obj_set_style_text_color(ui_Current_Time1, lv_color_hex(0x9F4400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Current_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Current_Time1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Current_Time1, -20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Current_Time1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Current_Time1, &ui_font_Montserrat_SemiBold_110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Current_Time1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Current_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Current_Time1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Current_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Prayers_List_Panel = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_Prayers_List_Panel, 342);
    lv_obj_set_height(ui_Prayers_List_Panel, 377);
    lv_obj_set_x(ui_Prayers_List_Panel, -10);
    lv_obj_set_y(ui_Prayers_List_Panel, -20);
    lv_obj_set_align(ui_Prayers_List_Panel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_Prayers_List_Panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Prayers_List_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Prayers_List_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Prayers_List_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Prayers_List_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Prayers_List_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Prayers_List_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Prayers_List_Panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fajr_Container = lv_obj_create(ui_Prayers_List_Panel);
    lv_obj_remove_style_all(ui_Fajr_Container);
    lv_obj_set_width(ui_Fajr_Container, 334);
    lv_obj_set_height(ui_Fajr_Container, 45);
    lv_obj_set_x(ui_Fajr_Container, -139);
    lv_obj_set_y(ui_Fajr_Container, -3);
    lv_obj_set_align(ui_Fajr_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Fajr_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Fajr_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fajr_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Fajr_Container, lv_color_hex(0xFFD29C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fajr_Container, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fajr_Label = lv_label_create(ui_Fajr_Container);
    lv_obj_set_width(ui_Fajr_Label, lv_pct(50));
    lv_obj_set_height(ui_Fajr_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Fajr_Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Fajr_Label, "Fajr");
    lv_obj_set_style_text_color(ui_Fajr_Label, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fajr_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Fajr_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fajr_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fajr_Time = lv_label_create(ui_Fajr_Container);
    lv_obj_set_width(ui_Fajr_Time, lv_pct(50));
    lv_obj_set_height(ui_Fajr_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Fajr_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Fajr_Time, "05:55 AM");
    lv_obj_set_style_text_color(ui_Fajr_Time, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fajr_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Fajr_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fajr_Time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sunrise_Container = lv_obj_create(ui_Prayers_List_Panel);
    lv_obj_remove_style_all(ui_Sunrise_Container);
    lv_obj_set_width(ui_Sunrise_Container, 334);
    lv_obj_set_height(ui_Sunrise_Container, 45);
    lv_obj_set_x(ui_Sunrise_Container, -139);
    lv_obj_set_y(ui_Sunrise_Container, -3);
    lv_obj_set_align(ui_Sunrise_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Sunrise_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Sunrise_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Sunrise_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Sunrise_Container, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sunrise_Container, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sunrise_Label = lv_label_create(ui_Sunrise_Container);
    lv_obj_set_width(ui_Sunrise_Label, lv_pct(50));
    lv_obj_set_height(ui_Sunrise_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Sunrise_Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Sunrise_Label, "Sunrise");
    lv_obj_set_style_text_color(ui_Sunrise_Label, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Sunrise_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Sunrise_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sunrise_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sunrise_Time = lv_label_create(ui_Sunrise_Container);
    lv_obj_set_width(ui_Sunrise_Time, lv_pct(50));
    lv_obj_set_height(ui_Sunrise_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Sunrise_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Sunrise_Time, "05:55 AM");
    lv_obj_set_style_text_color(ui_Sunrise_Time, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Sunrise_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Sunrise_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sunrise_Time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Duhur_Container = lv_obj_create(ui_Prayers_List_Panel);
    lv_obj_remove_style_all(ui_Duhur_Container);
    lv_obj_set_width(ui_Duhur_Container, 334);
    lv_obj_set_height(ui_Duhur_Container, 45);
    lv_obj_set_x(ui_Duhur_Container, -139);
    lv_obj_set_y(ui_Duhur_Container, -3);
    lv_obj_set_align(ui_Duhur_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Duhur_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Duhur_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Duhur_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Duhur_Container, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Duhur_Container, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Duhur_Label = lv_label_create(ui_Duhur_Container);
    lv_obj_set_width(ui_Duhur_Label, lv_pct(50));
    lv_obj_set_height(ui_Duhur_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Duhur_Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Duhur_Label, "Duhur");
    lv_obj_set_style_text_color(ui_Duhur_Label, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Duhur_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Duhur_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Duhur_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Duhur_Time = lv_label_create(ui_Duhur_Container);
    lv_obj_set_width(ui_Duhur_Time, lv_pct(50));
    lv_obj_set_height(ui_Duhur_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Duhur_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Duhur_Time, "05:55 AM");
    lv_obj_set_style_text_color(ui_Duhur_Time, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Duhur_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Duhur_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Duhur_Time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Asr_Container = lv_obj_create(ui_Prayers_List_Panel);
    lv_obj_remove_style_all(ui_Asr_Container);
    lv_obj_set_width(ui_Asr_Container, 334);
    lv_obj_set_height(ui_Asr_Container, 45);
    lv_obj_set_x(ui_Asr_Container, -139);
    lv_obj_set_y(ui_Asr_Container, -3);
    lv_obj_set_align(ui_Asr_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Asr_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Asr_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Asr_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Asr_Container, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Asr_Container, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Asr_Label = lv_label_create(ui_Asr_Container);
    lv_obj_set_width(ui_Asr_Label, lv_pct(50));
    lv_obj_set_height(ui_Asr_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Asr_Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Asr_Label, "Asr");
    lv_obj_set_style_text_color(ui_Asr_Label, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Asr_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Asr_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Asr_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Asr_Time = lv_label_create(ui_Asr_Container);
    lv_obj_set_width(ui_Asr_Time, lv_pct(50));
    lv_obj_set_height(ui_Asr_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Asr_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Asr_Time, "05:55 AM");
    lv_obj_set_style_text_color(ui_Asr_Time, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Asr_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Asr_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Asr_Time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Maghrib_Container = lv_obj_create(ui_Prayers_List_Panel);
    lv_obj_remove_style_all(ui_Maghrib_Container);
    lv_obj_set_width(ui_Maghrib_Container, 334);
    lv_obj_set_height(ui_Maghrib_Container, 45);
    lv_obj_set_x(ui_Maghrib_Container, -139);
    lv_obj_set_y(ui_Maghrib_Container, -3);
    lv_obj_set_align(ui_Maghrib_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Maghrib_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Maghrib_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Maghrib_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Maghrib_Container, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Maghrib_Container, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Maghrib_Label = lv_label_create(ui_Maghrib_Container);
    lv_obj_set_width(ui_Maghrib_Label, lv_pct(50));
    lv_obj_set_height(ui_Maghrib_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Maghrib_Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Maghrib_Label, "Maghrib");
    lv_obj_set_style_text_color(ui_Maghrib_Label, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Maghrib_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Maghrib_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Maghrib_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Maghrib_Time = lv_label_create(ui_Maghrib_Container);
    lv_obj_set_width(ui_Maghrib_Time, lv_pct(50));
    lv_obj_set_height(ui_Maghrib_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Maghrib_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Maghrib_Time, "05:55 AM");
    lv_obj_set_style_text_color(ui_Maghrib_Time, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Maghrib_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Maghrib_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Maghrib_Time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Isha_Container = lv_obj_create(ui_Prayers_List_Panel);
    lv_obj_remove_style_all(ui_Isha_Container);
    lv_obj_set_width(ui_Isha_Container, 334);
    lv_obj_set_height(ui_Isha_Container, 45);
    lv_obj_set_x(ui_Isha_Container, -139);
    lv_obj_set_y(ui_Isha_Container, -3);
    lv_obj_set_align(ui_Isha_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Isha_Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Isha_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Isha_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Isha_Container, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Isha_Container, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Isha_Label = lv_label_create(ui_Isha_Container);
    lv_obj_set_width(ui_Isha_Label, lv_pct(50));
    lv_obj_set_height(ui_Isha_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Isha_Label, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Isha_Label, "Sunrise");
    lv_obj_set_style_text_color(ui_Isha_Label, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Isha_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Isha_Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Isha_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Isha_Time = lv_label_create(ui_Isha_Container);
    lv_obj_set_width(ui_Isha_Time, lv_pct(50));
    lv_obj_set_height(ui_Isha_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Isha_Time, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Isha_Time, "05:55 AM");
    lv_obj_set_style_text_color(ui_Isha_Time, lv_color_hex(0x784000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Isha_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Isha_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Isha_Time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_Panel1 = lv_obj_create(ui_Prayers_Screen);
    lv_obj_set_width(ui_Left_Panel1, 70);
    lv_obj_set_height(ui_Left_Panel1, 480);
    lv_obj_set_align(ui_Left_Panel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Left_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Left_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Left_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Left_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Left_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Left_Panel1);
    lv_obj_set_width(ui_Button12, 50);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFBC58), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button12, lv_color_hex(0xEFA337), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button12, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button12, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button12, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button12, lv_color_hex(0xFFEDAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button12, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xEFA337), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_Button12, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Button12, lv_color_hex(0xFFBC58), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_Button12, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0xFFF2C7), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Button12, 100, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Button12, 40, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Button12, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label9 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_FontAwesome_Regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Left_Panel1);
    lv_obj_set_width(ui_Button11, 50);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFFBC58), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button11, lv_color_hex(0xEFA337), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button11, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button11, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button11, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button11, lv_color_hex(0xFFEDAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button11, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xEFA337), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_Button11, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Button11, lv_color_hex(0xFFBC58), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_Button11, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0xFFF2C7), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Button11, 100, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Button11, 40, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Button11, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label8 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_FontAwesome_Solid_24_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Left_Panel1);
    lv_obj_set_width(ui_Button13, 50);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xEFA337), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button13, lv_color_hex(0xFFBC58), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button13, lv_color_hex(0xFFEDAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0xFFF2C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button13, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xEFA337), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_Button13, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label14 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_FontAwesome_Solid_24_1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFi_Status1 = lv_img_create(ui_Prayers_Screen);
    lv_img_set_src(ui_WiFi_Status1, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_WiFi_Status1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_WiFi_Status1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_WiFi_Status1, -10);
    lv_obj_set_y(ui_WiFi_Status1, 10);
    lv_obj_set_align(ui_WiFi_Status1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WiFi_Status1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
