// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#include "../ui.h"

void ui_Setup_Screen_screen_init(void)
{
    ui_Setup_Screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Setup_Screen, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setup_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background1 = lv_img_create(ui_Setup_Screen);
    lv_img_set_src(ui_Background1, &ui_img_minaret_bg_png);
    lv_obj_set_width(ui_Background1, 800);
    lv_obj_set_height(ui_Background1, 480);
    lv_obj_set_align(ui_Background1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Panel_Header1 = lv_obj_create(ui_Setup_Screen);
    lv_obj_set_width(ui_Panel_Header1, 665);
    lv_obj_set_height(ui_Panel_Header1, 39);
    lv_obj_set_x(ui_Panel_Header1, -30);
    lv_obj_set_y(ui_Panel_Header1, 0);
    lv_obj_set_align(ui_Panel_Header1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFi_Networks = lv_dropdown_create(ui_Setup_Screen);
    lv_dropdown_set_options(ui_WiFi_Networks, "Scanning Networks");
    lv_obj_set_width(ui_WiFi_Networks, 386);
    lv_obj_set_height(ui_WiFi_Networks, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi_Networks, 19);
    lv_obj_set_y(ui_WiFi_Networks, -110);
    lv_obj_set_align(ui_WiFi_Networks, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFi_Networks, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_WiFi_Networks, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_WiFi_Networks, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_WiFi_Networks), &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFi_Password = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_WiFi_Password, 387);
    lv_obj_set_height(ui_WiFi_Password, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_WiFi_Password, 20);
    lv_obj_set_y(ui_WiFi_Password, -53);
    lv_obj_set_align(ui_WiFi_Password, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WiFi_Password, "Enter Wi-Fi Password");
    lv_textarea_set_one_line(ui_WiFi_Password, true);
    lv_textarea_set_password_mode(ui_WiFi_Password, true);
    lv_obj_set_style_text_font(ui_WiFi_Password, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ConnectButton = lv_btn_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ConnectButton, 120);
    lv_obj_set_height(ui_ConnectButton, 50);
    lv_obj_set_x(ui_ConnectButton, 302);
    lv_obj_set_y(ui_ConnectButton, -76);
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0xE58300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectButton, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Connect");

    ui_Label11 = lv_label_create(ui_Setup_Screen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 12);
    lv_obj_set_y(ui_Label11, -156);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Setup Wi-Fi");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x925E08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_Panel_Setup = ui_LeftPanel_create(ui_Setup_Screen);
    lv_obj_set_x(ui_Left_Panel_Setup, 0);
    lv_obj_set_y(ui_Left_Panel_Setup, 0);




    lv_obj_add_state(ui_comp_get_child(ui_Left_Panel_Setup, UI_COMP_LEFTPANEL_SETUP_BUTTON),
                     LV_STATE_FOCUSED);       /// States



    ui_Keyboard1 = lv_keyboard_create(ui_Setup_Screen);
    lv_obj_set_height(ui_Keyboard1, 262);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_shadow_color(ui_Keyboard1, lv_color_hex(0xFF8B00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Keyboard1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Keyboard1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Keyboard1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Keyboard1, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WiFi_Password, ui_event_WiFi_Password, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label10, ui_event_Label10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_WiFi_Password);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setup_Screen, ui_event_Setup_Screen, LV_EVENT_ALL, NULL);

}
