// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void OpaOn_Animation(lv_obj_t * TargetObject, int delay);
void OpaOff_Animation(lv_obj_t * TargetObject, int delay);
void ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuOut_Animation(lv_obj_t * TargetObject, int delay);
void ScreenOut_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
lv_obj_t * ui_Loading_Screen;
lv_obj_t * ui_Background2;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_Loading_Status_Text;
// CUSTOM VARIABLES


// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
lv_obj_t * ui_Main_Screen;
lv_obj_t * ui_Background;
lv_obj_t * ui_S1_Content_Panel;
lv_obj_t * ui_Next_Prayer_Panel;
lv_obj_t * ui_Next_Prayer;
lv_obj_t * ui_Next_Prayer_Remaining;
lv_obj_t * ui_Next_Prayer_Time;
lv_obj_t * ui_Current_Time;
lv_obj_t * ui_Weather_Condition_Panel;
lv_obj_t * ui_Weather_Image;
lv_obj_t * ui_Weather_Condition_Panel1;
lv_obj_t * ui_Current_Date;
lv_obj_t * ui_Left_Panel;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label5;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label6;
void ui_event_Settings_Button(lv_event_t * e);
lv_obj_t * ui_Settings_Button;
lv_obj_t * ui_Label3;
lv_obj_t * ui_WiFi_Status;
// CUSTOM VARIABLES


// SCREEN: ui_Setup_Screen
void ui_Setup_Screen_screen_init(void);
lv_obj_t * ui_Setup_Screen;
lv_obj_t * ui_Background1;
lv_obj_t * ui_Panel_Header1;
lv_obj_t * ui_Panel8;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label18;
lv_obj_t * ui_WiFi_Networks;
lv_obj_t * ui_WiFi_Password;
lv_obj_t * ui_Spinner1;
void ui_event_ConnectButton(lv_event_t * e);
lv_obj_t * ui_ConnectButton;
void ui_event_Label10(lv_event_t * e);
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES


// SCREEN: ui_Prayers_Screen
void ui_Prayers_Screen_screen_init(void);
lv_obj_t * ui_Prayers_Screen;
lv_obj_t * ui_Background3;
lv_obj_t * ui_S1_Content_Panel1;
lv_obj_t * ui_Next_Prayer_Panel1;
lv_obj_t * ui_Next_Prayer1;
lv_obj_t * ui_Next_Prayer_Remaining1;
lv_obj_t * ui_Next_Prayer_Time1;
lv_obj_t * ui_Date_Panel1;
lv_obj_t * ui_DT1;
lv_obj_t * ui_Label_Head_Temp1;
lv_obj_t * ui_Label_Printing_Head_Temp_1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_DT3_copy1;
lv_obj_t * ui_Label_Bed_Temp1;
lv_obj_t * ui_Label_Printing_Bed_Temp2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Current_Time1;
lv_obj_t * ui_Prayers_List_Panel;
lv_obj_t * ui_Fajr_Container;
lv_obj_t * ui_Fajr_Label;
lv_obj_t * ui_Fajr_Time;
lv_obj_t * ui_Sunrise_Container;
lv_obj_t * ui_Sunrise_Label;
lv_obj_t * ui_Sunrise_Time;
lv_obj_t * ui_Duhur_Container;
lv_obj_t * ui_Duhur_Label;
lv_obj_t * ui_Duhur_Time;
lv_obj_t * ui_Asr_Container;
lv_obj_t * ui_Asr_Label;
lv_obj_t * ui_Asr_Time;
lv_obj_t * ui_Maghrib_Container;
lv_obj_t * ui_Maghrib_Label;
lv_obj_t * ui_Maghrib_Time;
lv_obj_t * ui_Isha_Container;
lv_obj_t * ui_Isha_Label;
lv_obj_t * ui_Isha_Time;
lv_obj_t * ui_Left_Panel1;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label9;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label14;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label15;
lv_obj_t * ui_WiFi_Status1;
// CUSTOM VARIABLES


// SCREEN: ui_Settings_Screen
void ui_Settings_Screen_screen_init(void);
lv_obj_t * ui_Settings_Screen;
lv_obj_t * ui_Background4;
lv_obj_t * ui_Save_Button;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Panel1;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label4;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Settings_Content_Panel;
lv_obj_t * ui_Location_Settings_Container;
lv_obj_t * ui_Location_Label;
void ui_event_Latitude(lv_event_t * e);
lv_obj_t * ui_Latitude;
lv_obj_t * ui_Spacer1;
void ui_event_Longitude(lv_event_t * e);
lv_obj_t * ui_Longitude;
lv_obj_t * ui_Spacer;
void ui_event_Locate_Me(lv_event_t * e);
lv_obj_t * ui_Locate_Me;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Location_Name;
lv_obj_t * ui_Method_Setting_Container;
lv_obj_t * ui_Timezone_Label;
lv_obj_t * ui_Timezone_Dropdown;
lv_obj_t * ui_Method_Setting_Container1;
lv_obj_t * ui_Location_Label2;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_LocatorQR;
void ui_event_Keypad(lv_event_t * e);
lv_obj_t * ui_Keypad;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_icn_time_[2] = {&ui_img_icn_time_1_png, &ui_img_icn_time_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void OpaOn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 10);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void OpaOff_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ScreenIn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void MenuIn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void MenuOut_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 150);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ScreenOut_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Setup_Screen_screen_init);
        start_scan_task(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Prayers_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Prayers_Screen_screen_init);
    }
}

void ui_event_Settings_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Prayers_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Prayers_Screen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_Screen_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_Screen_screen_init);
        stop_scan_task(e);
    }
}

void ui_event_ConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connect_wifi(e);
    }
}

void ui_event_Label10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connect_wifi(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Setup_Screen_screen_init);
        start_scan_task(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Setup_Screen_screen_init);
        start_scan_task(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Prayers_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Prayers_Screen_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_Screen_screen_init);
        stop_scan_task(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Prayers_Screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Prayers_Screen_screen_init);
    }
}

void ui_event_Latitude(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keypad,  ui_Latitude);
        _ui_flag_modify(ui_Keypad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Longitude(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keypad,  ui_Longitude);
        _ui_flag_modify(ui_Keypad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Locate_Me(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        get_user_location(e);
    }
}

void ui_event_Keypad(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keypad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        keypad_ready(e);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_Keypad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        keypad_ready(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Loading_Screen_screen_init();
    ui_Main_Screen_screen_init();
    ui_Setup_Screen_screen_init();
    ui_Prayers_Screen_screen_init();
    ui_Settings_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Loading_Screen);
}
