// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#ifndef _AZAN_CLOCK_UI_H
#define _AZAN_CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void OpaOn_Animation(lv_obj_t * TargetObject, int delay);
void OpaOff_Animation(lv_obj_t * TargetObject, int delay);
void ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuOut_Animation(lv_obj_t * TargetObject, int delay);
void ScreenOut_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
extern lv_obj_t * ui_Main_Screen;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_Panel_Header;
extern lv_obj_t * ui_IMG_Wifi;
extern lv_obj_t * ui_IMG_PC;
extern lv_obj_t * ui_IMG_USB;
extern lv_obj_t * ui_S1_Content_Panel;
extern lv_obj_t * ui_Display_Time_S1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_DT1;
extern lv_obj_t * ui_Label_Printing_Time_1;
extern lv_obj_t * ui_Label_Time_1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_DT2;
extern lv_obj_t * ui_IMG_Tine_2;
extern lv_obj_t * ui_Label_Time_2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Display_Heat_S1;
extern lv_obj_t * ui_DT3;
extern lv_obj_t * ui_Label_Head_Temp;
extern lv_obj_t * ui_Label_Printing_Head_Temp_2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_DT3_copy;
extern lv_obj_t * ui_Label_Bed_Temp;
extern lv_obj_t * ui_Label_Printing_Bed_Temp1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_Setup_Screen
void ui_Setup_Screen_screen_init(void);
extern lv_obj_t * ui_Setup_Screen;
extern lv_obj_t * ui_Background1;
extern lv_obj_t * ui_Panel_Header1;
extern lv_obj_t * ui_IMG_Wifi1;
extern lv_obj_t * ui_IMG_PC1;
extern lv_obj_t * ui_IMG_USB1;
extern lv_obj_t * ui_Panel8;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_WiFi_Networks;
extern lv_obj_t * ui_WiFi_Password;
extern lv_obj_t * ui_Spinner1;
void ui_event_ConnectButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectButton;
void ui_event_Label10(lv_event_t * e);
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_minaret_bg_png);    // assets/minaret_bg.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_icn_pc_png);    // assets/icn_pc.png
LV_IMG_DECLARE(ui_img_icn_usb_png);    // assets/icn_usb.png
LV_IMG_DECLARE(ui_img_icn_time_2_png);    // assets/icn_time_2.png
LV_IMG_DECLARE(ui_img_rainy_weather_png);    // assets/rainy_weather.png
LV_IMG_DECLARE(ui_img_icn_time_1_png);    // assets/icn_time_1.png

// FONTS
LV_FONT_DECLARE(ui_font_FontAwesome_Brands_24);
LV_FONT_DECLARE(ui_font_FontAwesome_Regular_24);
LV_FONT_DECLARE(ui_font_FontAwesome_Solid_24_1);
LV_FONT_DECLARE(ui_font_FontAwesome_Solid_24_2);
LV_FONT_DECLARE(ui_font_Montserrat_SemiBold_60);
LV_FONT_DECLARE(ui_font_Montserrat_SemiBold_80);
LV_FONT_DECLARE(ui_font_Small_Font);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
