// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: azan_clock

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void change_screen(lv_event_t * e);
void start_scan_task(lv_event_t * e);
void connect_wifi(lv_event_t * e);
void save_settings(lv_event_t * e);
void get_user_location(lv_event_t * e);
void keypad_ready(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
